# Generated by Django 3.1.5 on 2021-02-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
            options={
                'verbose_name': 'friend',
                'verbose_name_plural': 'friends',
                'db_table': 'db_friend',
                'ordering': ['uid1'],
            },
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的ID')),
                ('sid', models.IntegerField(verbose_name='被滑动者的ID')),
                ('flag', models.CharField(choices=[('superlike', '上滑'), ('like', '右滑'), ('dislike', '左滑')], max_length=10)),
                ('date_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'swiped',
                'verbose_name_plural': 'swipeds',
                'db_table': 'db_swiped',
                'ordering': ['-date_time'],
                'get_latest_by': 'date_time',
            },
        ),
    ]
