# Generated by Django 2.2.12 on 2021-02-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=32, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(default=1, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(default=10, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=18, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=60, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(choices=[('0', '男'), ('1', '女')], max_length=8, verbose_name='匹配性别')),
                ('vibration', models.CharField(default=True, max_length=8, verbose_name='开启提示')),
                ('only_matche', models.CharField(default=True, max_length=8, verbose_name='不让未匹配的人看我的相册')),
                ('auto_play', models.CharField(default=True, max_length=8, verbose_name='自动播放视频')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=32, unique=True)),
                ('phone_num', models.CharField(max_length=16, unique=True)),
                ('sex', models.CharField(choices=[('0', '男性'), ('1', '女性')], max_length=8)),
                ('birth_year', models.IntegerField(default=1998, verbose_name='出生年')),
                ('birth_month', models.IntegerField(default=1, verbose_name='出生月')),
                ('birth_day', models.IntegerField(default=1, verbose_name='出生日')),
                ('avatar', models.CharField(max_length=256, verbose_name='个人形象')),
                ('location', models.CharField(max_length=32, verbose_name='常居地')),
            ],
        ),
    ]
