# Generated by Django 3.1.5 on 2021-02-06 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'user_info', 'verbose_name_plural': 'user_info'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['nickname'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='db_profile',
        ),
        migrations.AlterModelTable(
            name='user',
            table='db_user',
        ),
    ]
